[package]
name = "common_types"
authors = [""]
compiler_version = ">=0.18.0"
type = "lib"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.17.0", directory = "yarn-project/aztec-nr/aztec" }
