[package]
name = "attestor"
authors = [""]
compiler_version = ">=0.18.0"
type = "contract"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.24.0", directory = "noir-projects/aztec-nr/aztec" }
safe_math = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.24.0", directory = "noir-projects/aztec-nr/safe-math" }
authwit = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.24.0", directory = "noir-projects/aztec-nr/authwit" }

common_types = { path = "../common_types" }